// Static reference data for the VAT and Sales Tax calculators.
// Standard VAT/GST rates by country and US state sales-tax rates
// (state rate + population-weighted average local rate). Reference values —
// rates change; users can always override with a custom rate.

export type CountryVatRate = {
  country: string;
  type: "VAT" | "GST";
  rate: number; // standard rate %
  note?: string;
};

export const COUNTRY_VAT_RATES: CountryVatRate[] = [
  { country: "Albania", type: "VAT", rate: 20 },
  { country: "Argentina", type: "VAT", rate: 21, note: "Reduced 10.5%" },
  { country: "Australia", type: "GST", rate: 10 },
  { country: "Austria", type: "VAT", rate: 20, note: "Reduced 10%, 13%" },
  { country: "Bahrain", type: "VAT", rate: 10 },
  { country: "Bangladesh", type: "VAT", rate: 15 },
  { country: "Belgium", type: "VAT", rate: 21, note: "Reduced 6%, 12%" },
  { country: "Brazil", type: "VAT", rate: 17, note: "ICMS varies by state" },
  { country: "Bulgaria", type: "VAT", rate: 20, note: "Reduced 9%" },
  { country: "Canada", type: "GST", rate: 5, note: "Plus provincial HST/PST" },
  { country: "Chile", type: "VAT", rate: 19 },
  { country: "China", type: "VAT", rate: 13, note: "Reduced 9%, 6%" },
  { country: "Colombia", type: "VAT", rate: 19 },
  { country: "Croatia", type: "VAT", rate: 25, note: "Reduced 5%, 13%" },
  { country: "Cyprus", type: "VAT", rate: 19 },
  { country: "Czech Republic", type: "VAT", rate: 21, note: "Reduced 12%" },
  { country: "Denmark", type: "VAT", rate: 25 },
  { country: "Egypt", type: "VAT", rate: 14 },
  { country: "Estonia", type: "VAT", rate: 22 },
  { country: "Finland", type: "VAT", rate: 25.5, note: "Reduced 10%, 14%" },
  { country: "France", type: "VAT", rate: 20, note: "Reduced 5.5%, 10%" },
  { country: "Germany", type: "VAT", rate: 19, note: "Reduced 7%" },
  { country: "Greece", type: "VAT", rate: 24, note: "Reduced 6%, 13%" },
  { country: "Hungary", type: "VAT", rate: 27, note: "Highest in the world" },
  { country: "Iceland", type: "VAT", rate: 24, note: "Reduced 11%" },
  { country: "India", type: "GST", rate: 18, note: "Slabs 5%, 12%, 18%, 28%" },
  { country: "Indonesia", type: "VAT", rate: 11 },
  { country: "Ireland", type: "VAT", rate: 23, note: "Reduced 9%, 13.5%" },
  { country: "Israel", type: "VAT", rate: 18 },
  { country: "Italy", type: "VAT", rate: 22, note: "Reduced 4%, 5%, 10%" },
  { country: "Japan", type: "VAT", rate: 10, note: "Reduced 8% (food)" },
  { country: "Kenya", type: "VAT", rate: 16 },
  { country: "Latvia", type: "VAT", rate: 21 },
  { country: "Lithuania", type: "VAT", rate: 21 },
  { country: "Luxembourg", type: "VAT", rate: 17, note: "Lowest in the EU" },
  { country: "Malaysia", type: "VAT", rate: 8, note: "SST — sales & service tax" },
  { country: "Malta", type: "VAT", rate: 18 },
  { country: "Mexico", type: "VAT", rate: 16 },
  { country: "Netherlands", type: "VAT", rate: 21, note: "Reduced 9%" },
  { country: "New Zealand", type: "GST", rate: 15 },
  { country: "Nigeria", type: "VAT", rate: 7.5 },
  { country: "Norway", type: "VAT", rate: 25, note: "Reduced 12%, 15%" },
  { country: "Pakistan", type: "VAT", rate: 18 },
  { country: "Philippines", type: "VAT", rate: 12 },
  { country: "Poland", type: "VAT", rate: 23, note: "Reduced 5%, 8%" },
  { country: "Portugal", type: "VAT", rate: 23, note: "Reduced 6%, 13%" },
  { country: "Romania", type: "VAT", rate: 19, note: "Reduced 5%, 9%" },
  { country: "Saudi Arabia", type: "VAT", rate: 15 },
  { country: "Singapore", type: "GST", rate: 9, note: "Raised from 8% in 2024" },
  { country: "Slovakia", type: "VAT", rate: 23 },
  { country: "Slovenia", type: "VAT", rate: 22 },
  { country: "South Africa", type: "VAT", rate: 15 },
  { country: "South Korea", type: "VAT", rate: 10 },
  { country: "Spain", type: "VAT", rate: 21, note: "Reduced 4%, 10%" },
  { country: "Sri Lanka", type: "VAT", rate: 18 },
  { country: "Sweden", type: "VAT", rate: 25, note: "Reduced 6%, 12%" },
  { country: "Switzerland", type: "VAT", rate: 8.1, note: "Reduced 2.6%, 3.8%" },
  { country: "Taiwan", type: "VAT", rate: 5 },
  { country: "Thailand", type: "VAT", rate: 7 },
  { country: "Turkey", type: "VAT", rate: 20, note: "Reduced 1%, 10%" },
  { country: "UAE", type: "VAT", rate: 5 },
  { country: "United Kingdom", type: "VAT", rate: 20, note: "Reduced 5%, zero-rated food & books" },
  { country: "Vietnam", type: "VAT", rate: 10, note: "Temporarily 8% on some goods" },
];

export type StateTaxRate = {
  state: string;
  code: string;
  stateRate: number; // %
  avgLocalRate: number; // population-weighted average local %
};

// State + average local rates (Tax Foundation 2024–2025 data). Five states
// have no state-wide sales tax (AK/DE/MT/NH/OR — the "NOMAD" states), though
// some Alaska localities levy their own.
export const US_STATE_TAX_RATES: StateTaxRate[] = [
  { state: "Alabama", code: "AL", stateRate: 4, avgLocalRate: 5.29 },
  { state: "Alaska", code: "AK", stateRate: 0, avgLocalRate: 1.82 },
  { state: "Arizona", code: "AZ", stateRate: 5.6, avgLocalRate: 2.8 },
  { state: "Arkansas", code: "AR", stateRate: 6.5, avgLocalRate: 2.95 },
  { state: "California", code: "CA", stateRate: 7.25, avgLocalRate: 1.6 },
  { state: "Colorado", code: "CO", stateRate: 2.9, avgLocalRate: 4.91 },
  { state: "Connecticut", code: "CT", stateRate: 6.35, avgLocalRate: 0 },
  { state: "Delaware", code: "DE", stateRate: 0, avgLocalRate: 0 },
  { state: "Florida", code: "FL", stateRate: 6, avgLocalRate: 1 },
  { state: "Georgia", code: "GA", stateRate: 4, avgLocalRate: 3.39 },
  { state: "Hawaii", code: "HI", stateRate: 4, avgLocalRate: 0.5 },
  { state: "Idaho", code: "ID", stateRate: 6, avgLocalRate: 0.03 },
  { state: "Illinois", code: "IL", stateRate: 6.25, avgLocalRate: 2.61 },
  { state: "Indiana", code: "IN", stateRate: 7, avgLocalRate: 0 },
  { state: "Iowa", code: "IA", stateRate: 6, avgLocalRate: 0.94 },
  { state: "Kansas", code: "KS", stateRate: 6.5, avgLocalRate: 2.25 },
  { state: "Kentucky", code: "KY", stateRate: 6, avgLocalRate: 0 },
  { state: "Louisiana", code: "LA", stateRate: 5, avgLocalRate: 5.11 },
  { state: "Maine", code: "ME", stateRate: 5.5, avgLocalRate: 0 },
  { state: "Maryland", code: "MD", stateRate: 6, avgLocalRate: 0 },
  { state: "Massachusetts", code: "MA", stateRate: 6.25, avgLocalRate: 0 },
  { state: "Michigan", code: "MI", stateRate: 6, avgLocalRate: 0 },
  { state: "Minnesota", code: "MN", stateRate: 6.875, avgLocalRate: 1.17 },
  { state: "Mississippi", code: "MS", stateRate: 7, avgLocalRate: 0.06 },
  { state: "Missouri", code: "MO", stateRate: 4.225, avgLocalRate: 4.16 },
  { state: "Montana", code: "MT", stateRate: 0, avgLocalRate: 0 },
  { state: "Nebraska", code: "NE", stateRate: 5.5, avgLocalRate: 1.47 },
  { state: "Nevada", code: "NV", stateRate: 6.85, avgLocalRate: 1.39 },
  { state: "New Hampshire", code: "NH", stateRate: 0, avgLocalRate: 0 },
  { state: "New Jersey", code: "NJ", stateRate: 6.625, avgLocalRate: 0 },
  { state: "New Mexico", code: "NM", stateRate: 4.875, avgLocalRate: 2.73 },
  { state: "New York", code: "NY", stateRate: 4, avgLocalRate: 4.53 },
  { state: "North Carolina", code: "NC", stateRate: 4.75, avgLocalRate: 2.25 },
  { state: "North Dakota", code: "ND", stateRate: 5, avgLocalRate: 2.05 },
  { state: "Ohio", code: "OH", stateRate: 5.75, avgLocalRate: 1.49 },
  { state: "Oklahoma", code: "OK", stateRate: 4.5, avgLocalRate: 4.49 },
  { state: "Oregon", code: "OR", stateRate: 0, avgLocalRate: 0 },
  { state: "Pennsylvania", code: "PA", stateRate: 6, avgLocalRate: 0.34 },
  { state: "Rhode Island", code: "RI", stateRate: 7, avgLocalRate: 0 },
  { state: "South Carolina", code: "SC", stateRate: 6, avgLocalRate: 1.5 },
  { state: "South Dakota", code: "SD", stateRate: 4.2, avgLocalRate: 1.91 },
  { state: "Tennessee", code: "TN", stateRate: 7, avgLocalRate: 2.55 },
  { state: "Texas", code: "TX", stateRate: 6.25, avgLocalRate: 1.95 },
  { state: "Utah", code: "UT", stateRate: 6.1, avgLocalRate: 1.15 },
  { state: "Vermont", code: "VT", stateRate: 6, avgLocalRate: 0.36 },
  { state: "Virginia", code: "VA", stateRate: 5.3, avgLocalRate: 0.47 },
  { state: "Washington", code: "WA", stateRate: 6.5, avgLocalRate: 2.88 },
  { state: "Washington DC", code: "DC", stateRate: 6, avgLocalRate: 0 },
  { state: "West Virginia", code: "WV", stateRate: 6, avgLocalRate: 0.57 },
  { state: "Wisconsin", code: "WI", stateRate: 5, avgLocalRate: 0.7 },
  { state: "Wyoming", code: "WY", stateRate: 4, avgLocalRate: 1.44 },
];
