// Generated by scripts/sync-translations.mjs — do not edit by hand.
//
// Which languages each page has been translated into, read from the files in
// content/i18n/<page>/<lang>.json. Checked in because the language switcher
// runs in the browser and has to agree with what the server published.

import type { LanguageCode } from "./config";
import type { PageKey } from "./pages";

export const TRANSLATED_PAGES: Record<PageKey, LanguageCode[]> = {
  home: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  privacy: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  terms: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  contact: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  consultancy: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  products: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  tools: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  calculators: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
};

/**
 * Which languages each individual calculator and tool page is published in.
 *
 * Separate from TRANSLATED_PAGES because the directory of calculators can be
 * translated long before the twenty-nine pages it links to are, and a page is
 * only listed here once its own copy has been translated.
 */
export const TRANSLATED_ITEMS: Record<"calculators" | "tools", Record<string, LanguageCode[]>> = {
  calculators: {
    "gst-calculator": ["hi"],
    "profit-margin-calculator": [],
    "markup-calculator": [],
    "break-even-calculator": [],
    "food-cost-calculator": [],
    "discount-calculator": [],
    "loan-emi-calculator": [],
    "table-turnover-calculator": [],
    "take-home-salary-calculator": [],
    "income-tax-calculator": [],
    "gratuity-calculator": [],
    "online-order-commission-calculator": [],
    "online-menu-price-calculator": [],
    "recipe-costing-calculator": [],
    "liquor-cost-calculator": [],
    "tip-split-calculator": [],
    "inventory-turnover-calculator": [],
    "stock-reorder-point-calculator": [],
    "cac-calculator": [],
    "aov-calculator": [],
    "menu-engineering-calculator": [],
    "vat-calculator": [],
    "sales-tax-calculator": [],
    "roi-calculator": [],
    "depreciation-calculator": [],
    "payment-terms-calculator": [],
    "purchase-price-variance-calculator": [],
    "financial-ratio-calculator": [],
    "mdr-calculator": [],
  },
  tools: {
    "browser-based-pos": [],
    "invoice-generator": [],
    "upi-qr-generator": [],
    "upi-qr-split": [],
    "qr-menu-generator": [],
    "quotation-generator": [],
    "business-profile": [],
    "receipt-designer": [],
    "barcode-generator": [],
    "label-printer": [],
    "stock-register": [],
    "purchase-register": [],
    "supplier-book": [],
    "expense-tracker": [],
    "cash-book": [],
    "profit-dashboard": [],
    "customer-ledger": [],
    "appointment-book": [],
    "credit-note-generator": [],
    "debit-note-generator": [],
    "purchase-order-generator": [],
    "sales-order-generator": [],
    "chart-of-accounts": [],
    "journal-entry": [],
    "general-ledger": [],
    "bank-reconciliation": [],
    "bank-statement-analyzer": [],
    "trial-balance": [],
    "profit-loss-statement": [],
    "balance-sheet": [],
    "cash-flow-statement": [],
    "customer-statement": [],
    "invoice-aging-report": [],
    "accounts-payable-aging": [],
    "budget-vs-actual": [],
    "abc-analysis": [],
    "vendor-comparison": [],
  },
};
