// Generated by scripts/sync-translations.mjs — do not edit by hand.
//
// Which languages each page has been translated into, read from the files in
// content/i18n/<page>/<lang>.json. Checked in because the language switcher
// runs in the browser and has to agree with what the server published.

import type { LanguageCode } from "./config";
import type { PageKey } from "./pages";

export const TRANSLATED_PAGES: Record<PageKey, LanguageCode[]> = {
  home: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  privacy: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  terms: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  contact: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  consultancy: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  products: ["hi", "bn", "ta", "te"],
  tools: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
  calculators: ["hi", "bn", "ta", "te", "mr", "gu", "kn", "ml", "pa", "es", "fr", "ar", "pt", "id", "de", "zh"],
};
