import type { ComponentType } from "react";
import {
  Percent,
  TrendingUp,
  Tag,
  Scale,
  ChefHat,
  BadgePercent,
  Landmark,
  Clock,
  Calculator,
  Wallet,
  Receipt,
  PiggyBank,
  ShoppingCart,
  UtensilsCrossed,
  Martini,
  HandCoins,
  Boxes,
  RefreshCw,
  Target,
  CircleDollarSign,
  Smartphone,
  QrCode,
  Barcode,
  Printer,
  ClipboardList,
  Truck,
  CalendarDays,
  Paintbrush,
  BarChart3,
  BookUser,
  FileText,
  NotebookPen,
  Store,
  FileMinus,
  FilePlus,
  ListChecks,
  BookOpen,
  ArrowLeftRight,
  Layers,
  PieChart,
  GitCompare,
} from "lucide-react";

const icons: Record<string, ComponentType<{ className?: string }>> = {
  percent: Percent,
  "trending-up": TrendingUp,
  tag: Tag,
  scale: Scale,
  "chef-hat": ChefHat,
  "badge-percent": BadgePercent,
  landmark: Landmark,
  clock: Clock,
  wallet: Wallet,
  receipt: Receipt,
  "piggy-bank": PiggyBank,
  "shopping-cart": ShoppingCart,
  "utensils-crossed": UtensilsCrossed,
  martini: Martini,
  "hand-coins": HandCoins,
  boxes: Boxes,
  "refresh-cw": RefreshCw,
  target: Target,
  "circle-dollar-sign": CircleDollarSign,
  smartphone: Smartphone,
  "qr-code": QrCode,
  barcode: Barcode,
  printer: Printer,
  "clipboard-list": ClipboardList,
  truck: Truck,
  "calendar-days": CalendarDays,
  paintbrush: Paintbrush,
  "bar-chart-3": BarChart3,
  "book-user": BookUser,
  "file-text": FileText,
  "notebook-pen": NotebookPen,
  store: Store,
  "file-minus": FileMinus,
  "file-plus": FilePlus,
  "list-checks": ListChecks,
  "book-open": BookOpen,
  "arrow-left-right": ArrowLeftRight,
  layers: Layers,
  "chart-pie": PieChart,
  "git-compare": GitCompare,
};

export function CalculatorIcon({ name, className }: { name: string; className?: string }) {
  const Icon = icons[name] ?? Calculator;
  return <Icon className={className} aria-hidden="true" />;
}
